trigger:
  branches:
    include:
    - master

jobs:  
  - job:
    displayName: Build Test and Deploy Dev
    pool:
      vmImage: 'ubuntu-16.04'
      workspace:
        clean: all
    steps: 
    - bash: chmod +x ./scripts/build.sh && ./scripts/build.sh
      displayName: Build

    - bash: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh 
      displayName: Deploy