trigger:
  branches:
    include:
    - master

jobs:  
  - job: 
  displayName: Build Test and Deploy Dev
  pool:
  vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps: 
  - bash: ./scripts/build.sh
    displayName: Build